version: "3"

services:

  springboot-app:
    image: springboot-app
    restart: always
    build: .           # build from the Dockerfile in this directory
    ports:
      - "9090:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb        # wait for MySQL to start first

  react-app:
    build:
      context: ./src/main/webapp/reactjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_API_BASE_URL: "http://localhost:9090"
    depends_on:
      - springboot-app

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: miola
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql  # named volume for persistence

volumes:
  db-data:
