# MySQL config for Docker
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/miola
spring.datasource.username=${MYSQL_USER:sa}
spring.datasource.password=${MYSQL_PASSWORD:azerty}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Spring Data REST base path
spring.data.rest.base-path=/api

# Container-friendly port
server.port=8082

